version: '3.9'

services:
  library.webapi:
    image: ${DOCKER_REGISTRY-}librarywebapi
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    build:
      context: .
      dockerfile: KitchenRouter.WebAPI/Dockerfile
    depends_on: 
      - sqldatabase

  sqldatabase:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - PASSWORD=Passw0rd!
      - ACCEPT_EULA=Y